version: '2'
services:

  mysql:
    image: mysql:5.5
    container_name: deliverdb
    #command: --default-authentication-plugin=mysql_native_password
    volumes:
     - './sql:/docker-entrypoint-initdb.d'
    ports:
    - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"